ni9n/MachumCafe_CafeIn4

- Project/MachumCafe/MachumCafe/AppDelegate.swift
- Project/MachumCafe/MachumCafe/ModelCafe.swift
- Project/MachumCafe/MachumCafe/ModelUser.swift
ModelUser - Getter생성(Dictionary)
ModelCafe - Getter생성(Dictionary)
> [H] ModelUser & ModelCafe Getter 생성

- Project/MachumCafe/MachumCafe/AppDelegate.swift
- Project/MachumCafe/MachumCafe/LogInViewController.swift
- Project/MachumCafe/MachumCafe/ModelCafe.swift
- Project/MachumCafe/MachumCafe/ModelUser.swift
- Project/MachumCafe/MachumCafe/SignUpViewController.swift
LoginView - 로그인 성공 시 dismiss! mainView로 전환
appDelegate - application 실행 시 세션 확인하여 ModelUser에 업데이트
> [H] 로그인 성공시 dismiss와 AppDelegate에 application 실행 시 세션 확인

- Project/MachumCafe/MachumCafe/BookmarkView.storyboard
- Project/MachumCafe/MachumCafe/BookmarkViewController.swift
- Project/MachumCafe/MachumCafe/CafeDetailView.storyboard
- Project/MachumCafe/MachumCafe/ListView.storyboard
- Project/MachumCafe/MachumCafe/MainSideBarViewController.swift
* 로그인 상태에 따라 SideBarView 내 User 정보 표시
* Bookmark View Controller 연결
> [9] SideBarView 기능 업데이트

- Project/MachumCafe/MachumCafe/AppDelegate.swift
- Project/MachumCafe/MachumCafe/CafeDetailView.storyboard
- Project/MachumCafe/MachumCafe/CafeDetailViewController.swift
- Project/MachumCafe/MachumCafe/ListContainerView.storyboard
- Project/MachumCafe/MachumCafe/ListView.storyboard
- Project/MachumCafe/MachumCafe/ListViewController.swift
* ListView Cell 선택 시 해당하는 CafeDetailView 연결
> [H,9] Cafe detail view

- Project/MachumCafe/MachumCafe/AppDelegate.swift
- Project/MachumCafe/MachumCafe/CafeDetailView.storyboard
- Project/MachumCafe/MachumCafe/CafeDetailViewController.swift
- Project/MachumCafe/MachumCafe/ListViewController.swift
[B] Cafe detail view save working
디테일뷰 뿌려주는거 작업중입니다.
> [B] Cafe detail view save working

- Project/MachumCafe/MachumCafe.xcodeproj/project.pbxproj
- Project/MachumCafe/MachumCafe/AppDelegate.swift
- Project/MachumCafe/MachumCafe/MainSideBarViewController.swift
- Project/MachumCafe/MachumCafe/MainView.storyboard
- Project/MachumCafe/MachumCafe/SettingView.storyboard
- Project/MachumCafe/MachumCafe/SettingViewController.swift
> [9] Side bar view 배치 변경

- Project/MachumCafe/MachumCafe/AppDelegate.swift
- Project/MachumCafe/MachumCafe/CafeDetailViewController.swift
- Project/MachumCafe/MachumCafe/NetworkBookmark.swift
- Project/MachumCafe/MachumCafe/NetworkCafe.swift
- Project/MachumCafe/MachumCafe/NetworkUser.swift
network 전체 클래스 - response 데이터 담는 변수 이름 변경 & callback변수이름 변경(기존 result에서 직관적으로)
networkBookmark - 서버에서 변경된 response에 대한(userBookmark추가) 대응
> [H] Network 전체 변수이름 변경 & NetworkBookmark에 response userBookmark 추가

- Project/MachumCafe/MachumCafe/ListTableViewCell.swift
- Project/MachumCafe/MachumCafe/ListView.storyboard
- Project/MachumCafe/MachumCafe/ListViewController.swift
- Project/MachumCafe/MachumCafe/MainView.storyboard
- Project/MachumCafe/MachumCafe/StaticFunction.swift
* ListView내 Bookmark 추가, 삭제 기능 구현 완료
* UIAlertController Extension 구현
> [9] ListView 내 Bookmark 추가, 삭제 기능 구현

- Project/MachumCafe/MachumCafe/CafeDetailView.storyboard
- Project/MachumCafe/MachumCafe/CafeDetailViewController.swift
- Project/MachumCafe/MachumCafe/ListViewController.swift
* ListView에서 Cell 선택 시 CafeDetailView로 Index 값을 넘기는 방식에서 ModelCafe 데이터를 넘기는 방식으로 변경
> [9] Data 받아오는 방식 변경 (index -> ModelCafe)

- Project/MachumCafe/MachumCafe/BookmarkView.storyboard
- Project/MachumCafe/MachumCafe/BookmarkViewCell.swift
- Project/MachumCafe/MachumCafe/BookmarkViewController.swift
- Project/MachumCafe/MachumCafe/CafeDetailViewController.swift
- Project/MachumCafe/MachumCafe/ExtentionUIColorClass.swift
- Project/MachumCafe/MachumCafe/ListContainerView.storyboard
- Project/MachumCafe/MachumCafe/ListView.storyboard
- Project/MachumCafe/MachumCafe/ListViewController.swift
- Project/MachumCafe/MachumCafe/MainSideBarViewController.swift
- Project/MachumCafe/MachumCafe/MainView.storyboard
- Project/MachumCafe/MachumCafe/StaticFunction.swift
> [9] Bookmark view Update

- Project/MachumCafe/MachumCafe/AppDelegate.swift
- Project/MachumCafe/MachumCafe/BookmarkViewController.swift
- Project/MachumCafe/MachumCafe/MainView.storyboard
- Project/MachumCafe/MachumCafe/NetworkBookmark.swift
- Project/MachumCafe/MachumCafe/NetworkCafe.swift
- Project/MachumCafe/MachumCafe/NetworkUser.swift
- NetworkBookmark, NetworkUser, NetworkCafe
- SwiftyJSON으로 리팩토링
- NetworkCafe
- getImageData 함수 콜백 추가
> [H] Network 전체 클래스 SwiftyJSON으로 리팩토링 & getImageData 함수 콜백 추가

- Project/MachumCafe/MachumCafe/LogInViewController.swift
- Project/MachumCafe/MachumCafe/SignUpViewController.swift
- Project/MachumCafe/MachumCafe/StaticFunction.swift
- StaticFunction
- UIAlertController extension 추가
- LoginView & SignUpView
- extension적용
> [H] UIAlertController extension 추가(oneButtonAlert)

- Project/MachumCafe/MachumCafe/NetworkBookmark.swift
- Project/MachumCafe/MachumCafe/SettingViewController.swift
- Project/MachumCafe/MachumCafe/SignUpViewController.swift
- Project/MachumCafe/MachumCafe/StaticFunction.swift
- NetworkBookmark
- setMyBookmark 함수 비로그인 시 런타임 에러 해결
- settingView 
- 로그아웃 시 Alert 추가
- MARK 작성해놓았는데 구제이 확인 및 해결 부탁
> [H] NetworkBookmark 런타임에러 해결 & 로그아웃 버튼 수정

- Project/MachumCafe/MachumCafe/BookmarkView.storyboard
- Project/MachumCafe/MachumCafe/BookmarkViewCell.swift
- Project/MachumCafe/MachumCafe/BookmarkViewController.swift
- Project/MachumCafe/MachumCafe/CafeDetailViewController.swift
- Project/MachumCafe/MachumCafe/ListViewController.swift
- Project/MachumCafe/MachumCafe/MainSideBarViewController.swift
- Project/MachumCafe/MachumCafe/SettingView.storyboard
- Project/MachumCafe/MachumCafe/SettingViewController.swift
- Project/MachumCafe/MachumCafe/SuggestionView.storyboard
- Project/MachumCafe/MachumCafe/SuggestionViewController.swift
> [9] 여러 ViewController 버그 수정 및 코드 보완

- Project/MachumCafe/MachumCafe.xcodeproj/project.pbxproj
- Project/MachumCafe/MachumCafe/Info.plist
- Project/MachumCafe/MachumCafe/ListMapView.storyboard
- Project/MachumCafe/MachumCafe/ListMapViewController.swift
* ListMapView Cafe정보 View AutoLayout 설정
* ListMapView내 ModelCafe Data 보여주기
* ListMapView에서 카페 터치 시 CafeDetailView로 데이터 넘기기
> [9] ListMapView Data 불러와서 보여주기, 터치 시 CafeDetailView 연결, AutoLayout 설정 등

- Project/MachumCafe/MachumCafe.xcodeproj/project.pbxproj
- Project/MachumCafe/MachumCafe/ListMapView.storyboard
- Project/MachumCafe/MachumCafe/ListMapViewController.swift
- Project/MachumCafe/MachumCafe/LocationLabelView.swift
- Project/MachumCafe/MachumCafe/ModelLocation.swift
- Project/MachumCafe/MachumCafe/SetLocationMapViewController.swift
* ListMapView 내 CafeInfoView Animation 추가
* 내 위치 설정 저장을 위한 ModelLocation Singleton 생성
* LocationLabel 내 위치 변경에 따라 해당 주소로 새로고침 되는 코드 추가
> [9] MapView관련 Code 보완

- Project/MachumCafe/MachumCafe.xcodeproj/project.pbxproj
- Project/MachumCafe/MachumCafe/ListContainerView.storyboard
- Project/MachumCafe/MachumCafe/LocationLabelView.swift
- Project/MachumCafe/MachumCafe/LocationLabelView.xib
- Project/MachumCafe/MachumCafe/MainView.storyboard
- Project/MachumCafe/MachumCafe/MainViewController.swift
- Project/MachumCafe/MachumCafe/ModelLocation.swift
- Project/MachumCafe/MachumCafe/NetworkMap.swift
- Project/MachumCafe/MachumCafe/SetLocationMapView.storyboard
- Project/MachumCafe/MachumCafe/SetLocationMapViewController.swift
> [9] 일부 View 코드 보완 및 개선

- Project/MachumCafe/MachumCafe/AppDelegate.swift
- Project/MachumCafe/MachumCafe/BookmarkViewController.swift
- Project/MachumCafe/MachumCafe/CafeDetailView.storyboard
- Project/MachumCafe/MachumCafe/CafeDetailViewController.swift
- Project/MachumCafe/MachumCafe/ListMapViewController.swift
- Project/MachumCafe/MachumCafe/ListViewController.swift
- Project/MachumCafe/MachumCafe/ModelCafe.swift
- Project/MachumCafe/MachumCafe/NetworkBookmark.swift
- Project/MachumCafe/MachumCafe/NetworkCafe.swift
- Project/MachumCafe/MachumCafe/NetworkMap.swift
> [H] Network

- Project/MachumCafe/MachumCafe/AppDelegate.swift
- Project/MachumCafe/MachumCafe/NetworkBookmark.swift
- Project/MachumCafe/MachumCafe/NetworkCafe.swift
- Project/MachumCafe/MachumCafe/SetLocationMapViewController.swift
- NetworkCafe & NetworkBookmark
- DB구조 변경으로 인해 response 데이터 수정
- NetworkCafe
- 현위치 반경 1km 내 카페목록 불러오기는 함수 추가
> [H] NetworkCafe 반경 1km 내 카페 목록 불러오기로 수정

- Project/MachumCafe/MachumCafe.xcodeproj/project.pbxproj
- Project/MachumCafe/MachumCafe/SuggestionCategoryTableViewCell.swift
- Project/MachumCafe/MachumCafe/SuggestionImagePickerViewCollectionViewCell.swift
- Project/MachumCafe/MachumCafe/SuggestionImagePickerViewController.swift
- Project/MachumCafe/MachumCafe/SuggestionView.storyboard
- Project/MachumCafe/MachumCafe/SuggestionViewController.swift
- Scrum/README.md
SuggestionView
이미지피커 컬렉션뷰 구현
선택한 이미지피커 미리보기
> [B] Suggestion & Imagepicker

- Project/MachumCafe/MachumCafe/LogInViewController.swift
- Project/MachumCafe/MachumCafe/SignUpViewController.swift
> [H] 회원가입 시 빈칸 있을경우 Alert 생성

- Project/MachumCafe/MachumCafe/Info.plist
- Project/MachumCafe/MachumCafe/ListView.storyboard
- Project/MachumCafe/MachumCafe/ListViewController.swift
- Project/MachumCafe/MachumCafe/LogInViewController.swift
- Project/MachumCafe/MachumCafe/SettingViewController.swift
- Project/MachumCafe/MachumCafe/SignUpViewController.swift
> [9] 일부 View 코드 수정

- Project/MachumCafe/MachumCafe/ListContainerViewController.swift
- Project/MachumCafe/MachumCafe/ListMapViewController.swift
- Project/MachumCafe/MachumCafe/ListView.storyboard
- Project/MachumCafe/MachumCafe/ListViewController.swift
- Project/MachumCafe/MachumCafe/MainViewController.swift
- Project/MachumCafe/MachumCafe/SetLocationMapViewController.swift
- ListViewController
- cell 올라올때 NetworkGetImageData 함수 호출
> [H] List view

- Project/MachumCafe/MachumCafe.xcodeproj/project.pbxproj
- Project/MachumCafe/MachumCafe/CafeDetailView.storyboard
- Project/MachumCafe/MachumCafe/CafeDetailViewController.swift
- Project/MachumCafe/MachumCafe/ListMapView.storyboard
- Project/MachumCafe/MachumCafe/ListView.storyboard
- Project/MachumCafe/MachumCafe/ReviewTableViewCell.swift
- Project/MachumCafe/MachumCafe/ReviewView.storyboard
- Project/MachumCafe/MachumCafe/ReviewViewController.swift
> [J]Review view

- Project/MachumCafe/MachumCafe/AppDelegate.swift
- Project/MachumCafe/MachumCafe/BookmarkViewController.swift
- Project/MachumCafe/MachumCafe/CafeDetailViewController.swift
- Project/MachumCafe/MachumCafe/ListViewController.swift
- Project/MachumCafe/MachumCafe/NetworkBookmark.swift
- Project/MachumCafe/MachumCafe/NetworkCafe.swift
- NetworkBookmark
- Bookmark Set & Get 함수 리팩토링 ( 서버도 수정했어요 )
- BookmarkViewController
- 코드 리팩토링(이미지 불러오기, get함수 사용 등)
- DetailView & ListView
- Bookmark 관련 서버 수정에 맞게 변경
> [H] NetworkBookmark 리팩토링 & 즐겨찾기 이미지 불러오기 수정

- Project/MachumCafe/MachumCafe/SuggestionCategory.swift
- Project/MachumCafe/MachumCafe/SuggestionCategoryTableViewCell.swift
- Project/MachumCafe/MachumCafe/SuggestionImagePickerViewController.swift
- Project/MachumCafe/MachumCafe/SuggestionView.storyboard
- Project/MachumCafe/MachumCafe/SuggestionViewController.swift
이미지 미리보기 삭제 기능 추가
선택된 이미지 클릭-> 어레이내에서 삭제
> [B] imagepreview remove active

- Project/MachumCafe/MachumCafe/SetLocationMapViewController.swift
* 추가 과제
* SearchBar 터치 시 Cancel 버튼 없애기
> [9] SetLocationView 내 검색 기능 추가

- Project/MachumCafe/MachumCafe/FilterViewCell.swift
- Project/MachumCafe/MachumCafe/SetLocationMapViewController.swift
- Project/MachumCafe/MachumCafe/SuggestionCategory.swift
- Project/MachumCafe/MachumCafe/SuggestionImagePickerViewController.swift
- Project/MachumCafe/MachumCafe/SuggestionView.storyboard
- Project/MachumCafe/MachumCafe/SuggestionViewController.swift
* SuggestionView 주소 검색기능 추가 (좌표, 한글 주소 입력)
* SetLocationView Cancel 버튼 Hide 구현 중
> [9] Suggestion view

- Project/MachumCafe/MachumCafe/ListContainerViewController.swift
- Project/MachumCafe/MachumCafe/LocationLabelView.swift
- Project/MachumCafe/MachumCafe/MainSideBarViewController.swift
- Project/MachumCafe/MachumCafe/MainViewController.swift
- Project/MachumCafe/MachumCafe/StaticFunction.swift
- Project/MachumCafe/MachumCafe/SuggestionViewController.swift
* 각 Storyboard 파일 UIStoryboard Extension 으로 초기화
> [9] 각 Storyboard 파일 UIStoryboard Extension 화

- Project/MachumCafe/MachumCafe/AppDelegate.swift
- Project/MachumCafe/MachumCafe/FilterViewController.swift
- Project/MachumCafe/MachumCafe/ListContainerViewController.swift
- Project/MachumCafe/MachumCafe/ListMapViewController.swift
- Project/MachumCafe/MachumCafe/ModelCafe.swift
- Project/MachumCafe/MachumCafe/ModelLocation.swift
- Project/MachumCafe/MachumCafe/SetLocationMapViewController.swift
- Project/MachumCafe/MachumCafe/StaticFunction.swift
> [9] 위치 변경 또는 이동 시 추가 카페 목록 Load

- Project/MachumCafe/MachumCafe.xcodeproj/project.pbxproj
- Project/MachumCafe/MachumCafe/AppDelegate.swift
- Project/MachumCafe/MachumCafe/BookmarkViewController.swift
- Project/MachumCafe/MachumCafe/CafeDetailViewController.swift
- Project/MachumCafe/MachumCafe/FilterCollectionViewCell.swift
- Project/MachumCafe/MachumCafe/FilterCollectionViewCell.xib
- Project/MachumCafe/MachumCafe/FilterView.storyboard
- Project/MachumCafe/MachumCafe/FilterViewCell.swift
- Project/MachumCafe/MachumCafe/FilterViewController.swift
- Project/MachumCafe/MachumCafe/ListContainerViewController.swift
- Project/MachumCafe/MachumCafe/ListViewController.swift
- Project/MachumCafe/MachumCafe/MainView.storyboard
- Project/MachumCafe/MachumCafe/MainViewController.swift
- Project/MachumCafe/MachumCafe/ModelCafe.swift
- Project/MachumCafe/MachumCafe/SuggestionView.storyboard
- Project/MachumCafe/MachumCafe/SuggestionViewController.swift
> Refactoring

- Project/MachumCafe/MachumCafe/CafeDetailViewController.swift
- Project/MachumCafe/MachumCafe/NetworkCafe.swift
> [H] Refactoring

- Project/MachumCafe/MachumCafe/SuggestionViewController.swift
> [H] http통신 시에 설정한 주소의 좌표 전송

- Project/MachumCafe/MachumCafe/BookmarkViewController.swift
- Project/MachumCafe/MachumCafe/CafeDetailViewController.swift
- Project/MachumCafe/MachumCafe/ListViewController.swift
- Project/MachumCafe/MachumCafe/NetworkBookmark.swift
- Project/MachumCafe/MachumCafe/NetworkCafe.swift
- Project/MachumCafe/MachumCafe/WriteReviewViewController.swift
> [H] 즐겨찾기 & 리뷰 등록 시 서버의 result로 세션 확인 하던 코드 클라이언트 내에서 확인하는 것으로 변경

- Project/MachumCafe/MachumCafe/ListContainerView.storyboard
- Project/MachumCafe/MachumCafe/ListContainerViewController.swift
- Project/MachumCafe/MachumCafe/ListView.storyboard
- Project/MachumCafe/MachumCafe/ListViewController.swift
- Project/MachumCafe/MachumCafe/StaticFunction.swift
> [9] ListView 코드 업데이트

- Project/MachumCafe/MachumCafe/BookmarkViewController.swift
- Project/MachumCafe/MachumCafe/CafeDetailViewController.swift
- Project/MachumCafe/MachumCafe/FilterViewController.swift
- Project/MachumCafe/MachumCafe/ListContainerViewController.swift
- Project/MachumCafe/MachumCafe/ListMapViewController.swift
- Project/MachumCafe/MachumCafe/ListViewController.swift
- Project/MachumCafe/MachumCafe/ReviewViewController.swift
- Project/MachumCafe/MachumCafe/SignUpViewController.swift
- Project/MachumCafe/MachumCafe/StaticFunction.swift
- Project/MachumCafe/MachumCafe/SuggestionViewController.swift
extension에 구현되어 있던 기본 클래스의 메서드들 위치 변경
코드 스타일 규칙에 맞게 수정
> [H] extension에 구현되어 있던 불필요 기본메서드들 기본 클래스로 이동

- Project/MachumCafe/MachumCafe/ListViewController.swift
- Project/MachumCafe/MachumCafe/ModelCafe.swift
- Project/MachumCafe/MachumCafe/NetworkBookmark.swift
- Project/MachumCafe/MachumCafe/NetworkCafe.swift
- Project/MachumCafe/MachumCafe/SuggestionViewController.swift
> [H] 카페정보에 평점 항목 추가, ModelCafe, Network 변경 내용에 대한 대응

- Project/MachumCafe/MachumCafe/BookmarkView.storyboard
- Project/MachumCafe/MachumCafe/BookmarkViewCell.swift
- Project/MachumCafe/MachumCafe/BookmarkViewController.swift
- collectionView Flow Layout 추가
- cell간 간격 조절
- 디자인 수정
- AutoLayout 정리
> [B] 셀+라벨 오토레이아웃 & 디자인수정

- Project/MachumCafe/MachumCafe/CafeDetailViewController.swift
- Project/MachumCafe/MachumCafe/NetworkAdmin.swift
> [H] 페업신고 기능 활성화, 폐업신고 network 함수 생성

- Project/MachumCafe/MachumCafe/LogIn&SignUpView.storyboard
- Project/MachumCafe/MachumCafe/SignUpViewController.swift
- Project/MachumCafe/MachumCafe/StaticFunction.swift
> [H] 비밀번호 유효성(6자 이상) 구현, password text field placeholder 추가

- Project/MachumCafe/MachumCafe/LogIn&SignUpView.storyboard
로그인 Autolayout 추가
스택뷰 추가
5.6.7+까지 오토레이아웃 완성-!
> [B] 로그인 Autolayout 추가

- Project/MachumCafe/MachumCafe/MainView.storyboard
> [B] 메인+사이드바 오토레이아웃 수정
